"""Causal closure for a sparse cross-version functional delta.

This module implements the mechanism that distinguishes the current Design 1
candidate from a sampled KV cache, a learned mapping, or a control-variate
estimator alone.  The complete Parent cache remains the exact control path.
Current carriers are processed in chronological order and, at every layer,
read two things:

* the complete causal Parent prefix; and
* the signed Current-minus-Parent response represented by earlier carriers.

The resulting upper-layer Current carrier is therefore generated by the
functional delta constructed so far.  It never reads an Exact Current
upper-layer prefix.  With one carrier per source position and unit mass this
recursion is exactly equivalent to constructing the Current cache; compact
support is the approximation being tested.

The first implementation is deliberately scoped to the repository's legacy
ELU+1, no-relative-bias reader.  Its paired native-attention atoms are more
general than the affine moment compiler, but additive response correction is
not silently claimed for softmax attention.
"""

from __future__ import annotations

from dataclasses import dataclass

import torch

from hstu_kvcache.models import HSTUKVCache
from insight_two.address_response_memory import AddressLandmarkSelection
from insight_two.cone_response_memory import (
    _block_update,
    _native_prefix_heads,
    _native_self_heads,
)
from insight_two.paired_region_delta import (
    CurrentLayer0Projection,
    _validate_model,
    _validate_parent_cache,
    project_full_current_layer0,
)
from insight_two.signed_response_memory import OracleSignedResponseMemory


@dataclass(frozen=True)
class ChronologicalCarrierPartition:
    """A landmark partition reordered into causal source-position order."""

    source_length: int
    positions: torch.Tensor
    masses: torch.Tensor
    assignments: torch.Tensor

    @property
    def carrier_count(self) -> int:
        return int(self.positions.numel())


@dataclass(frozen=True)
class CausalDeltaClosureBuild:
    """Auditable outputs of one legal recursive carrier construction."""

    memory: OracleSignedResponseMemory
    current_carriers: HSTUKVCache
    partition: ChronologicalCarrierPartition
    represented_prefix_fractions: torch.Tensor
    recursive_delta_enabled: bool
    layer0_prefix_mode: str


def chronological_carrier_partition(
    selection: AddressLandmarkSelection,
) -> ChronologicalCarrierPartition:
    """Reindex a selection without changing its source-to-center assignment."""

    positions = selection.selected_positions
    assignments = selection.assignments
    if positions.ndim != 1 or positions.numel() < 1:
        raise ValueError("selected positions must be a non-empty vector")
    if assignments.shape != (selection.source_length,):
        raise ValueError("selection assignments differ from source length")
    if torch.unique(positions).numel() != positions.numel():
        raise ValueError("selected positions must be unique")
    if bool((positions < 0).any()) or bool((positions >= selection.source_length).any()):
        raise ValueError("selected position is outside source history")
    carriers = int(positions.numel())
    if bool((assignments < 0).any()) or bool((assignments >= carriers).any()):
        raise ValueError("selection assignment is outside carrier range")

    order = torch.argsort(positions)
    sorted_positions = positions.index_select(0, order)
    old_to_new = torch.empty_like(order)
    old_to_new[order] = torch.arange(carriers, device=order.device)
    sorted_assignments = old_to_new.index_select(0, assignments.to(dtype=torch.long))
    sorted_masses = torch.bincount(sorted_assignments, minlength=carriers)
    if not torch.equal(
        sorted_masses,
        selection.cluster_masses.index_select(0, order),
    ):
        raise ValueError("selection masses do not match assignments")
    if bool((sorted_masses <= 0).any()):
        raise ValueError("every carrier must represent positive source mass")
    return ChronologicalCarrierPartition(
        source_length=selection.source_length,
        positions=sorted_positions,
        masses=sorted_masses,
        assignments=sorted_assignments,
    )


def _validate_raw_history(
    parent_cache: HSTUKVCache,
    item_ids: torch.Tensor,
    behaviors: torch.Tensor,
    time_deltas: torch.Tensor,
) -> None:
    expected = (1, parent_cache.seq_len)
    if item_ids.shape != expected:
        raise ValueError(f"item_ids must have shape {expected}")
    if behaviors.shape != expected or time_deltas.shape != expected:
        raise ValueError("raw history tensor shapes differ")


def _flatten_heads(values: torch.Tensor) -> torch.Tensor:
    if values.ndim != 4 or values.shape[0] != 1 or values.shape[2] != 1:
        raise ValueError("projected carrier must have shape [1,H,1,D]")
    return values.transpose(1, 2).reshape(1, 1, -1)


def _heads(values: torch.Tensor, *, heads: int, head_dim: int) -> torch.Tensor:
    if values.ndim != 3 or values.shape[0] != 1:
        raise ValueError("carrier values must have shape [1,R,width]")
    if values.shape[-1] != heads * head_dim:
        raise ValueError("carrier width differs from attention head layout")
    return values.view(1, values.shape[1], heads, head_dim).transpose(1, 2)


def _weighted_native_pair_delta(
    attention,
    q: torch.Tensor,
    current_k: torch.Tensor,
    current_v: torch.Tensor,
    parent_k: torch.Tensor,
    parent_v: torch.Tensor,
    weights: torch.Tensor,
) -> torch.Tensor:
    """Read weighted paired atoms with the model's native pointwise kernel."""

    if current_k.shape != current_v.shape or current_k.shape != parent_k.shape:
        raise ValueError("paired carrier K/V shapes differ")
    if current_k.shape != parent_v.shape:
        raise ValueError("paired Parent K/V shapes differ")
    if weights.shape != (current_k.shape[1],):
        raise ValueError("prefix carrier weights differ from carrier width")
    if current_k.shape[1] == 0:
        return torch.zeros_like(q)
    current_keys = _heads(
        current_k, heads=attention.num_heads, head_dim=attention.head_dim
    )
    current_values = _heads(
        current_v, heads=attention.num_heads, head_dim=attention.head_dim
    )
    parent_keys = _heads(
        parent_k, heads=attention.num_heads, head_dim=attention.head_dim
    )
    parent_values = _heads(
        parent_v, heads=attention.num_heads, head_dim=attention.head_dim
    )
    current_logits = torch.matmul(q, current_keys.transpose(-2, -1)) * attention.scale
    parent_logits = torch.matmul(q, parent_keys.transpose(-2, -1)) * attention.scale
    current_activation = attention._activate(current_logits)
    parent_activation = attention._activate(parent_logits)
    weight = weights.to(device=q.device, dtype=q.dtype).view(1, 1, 1, -1)
    current_response = torch.matmul(
        attention.attn_dropout(current_activation * weight), current_values
    )
    parent_response = torch.matmul(
        attention.attn_dropout(parent_activation * weight), parent_values
    )
    return current_response - parent_response


def build_native_pair_memory(
    current_carriers: HSTUKVCache,
    parent_cache: HSTUKVCache,
    partition: ChronologicalCarrierPartition,
) -> OracleSignedResponseMemory:
    """Package legal paired carrier state for the existing native reader."""

    if parent_cache.k.ndim != 4 or parent_cache.k.shape != parent_cache.v.shape:
        raise ValueError("Parent cache must contain matching [L,1,N,W] K/V")
    if parent_cache.k.shape[1] != 1 or parent_cache.k.shape[2] != parent_cache.seq_len:
        raise ValueError("Parent cache batch/history layout differs")
    if current_carriers.k.ndim != 4 or current_carriers.k.shape != current_carriers.v.shape:
        raise ValueError("Current carriers must contain matching [L,1,R,W] K/V")
    if current_carriers.k.shape[:3] != (
        parent_cache.k.shape[0],
        1,
        partition.carrier_count,
    ):
        raise ValueError("Current carrier layout differs from Parent/partition")
    positions = partition.positions.to(device=parent_cache.k.device, dtype=torch.long)
    parent_k = parent_cache.k.index_select(2, positions)
    parent_v = parent_cache.v.index_select(2, positions)
    masses = partition.masses.to(device=parent_v.device, dtype=parent_v.dtype)
    weighted = masses.view(1, 1, partition.carrier_count, 1)
    return OracleSignedResponseMemory(
        keys=torch.cat((current_carriers.k, parent_k), dim=2).detach(),
        signed_values=torch.cat(
            (current_carriers.v * weighted, -parent_v * weighted), dim=2
        ).detach(),
        source_positions=torch.cat((positions, positions), dim=0).detach(),
        sample_positions=positions.detach(),
        inverse_inclusion_probabilities=masses.detach(),
        source_length=parent_cache.seq_len,
    )


@torch.inference_mode()
def build_causal_delta_closure(
    model,
    parent_cache: HSTUKVCache,
    item_ids: torch.Tensor,
    behaviors: torch.Tensor,
    time_deltas: torch.Tensor,
    selection: AddressLandmarkSelection,
    *,
    current_layer0: CurrentLayer0Projection | None = None,
    recursive_delta: bool = True,
    layer0_prefix_mode: str = "paired_closure",
) -> CausalDeltaClosureBuild:
    """Generate sparse Current carriers through a causal functional ledger.

    ``recursive_delta=False`` is the matched Parent-conditioned ablation.  It
    uses the same positions, masses, full Parent prefix, and Current model but
    prevents earlier carrier deltas from influencing later carriers.

    The primary ``paired_closure`` mode deliberately gives layer-0 carriers
    the same sparse functional prefix that serving queries will read.  The
    dependency-free full Current layer-0 projection supplies exact carrier
    K/V and selector features, but is not substituted as a different dense
    reader state.  ``exact_current`` is a locally-more-exact but potentially
    representation-inconsistent ablation.
    """

    _validate_model(model)
    _validate_parent_cache(model, parent_cache)
    _validate_raw_history(parent_cache, item_ids, behaviors, time_deltas)
    if selection.source_length != parent_cache.seq_len:
        raise ValueError("selection and Parent history lengths differ")
    if layer0_prefix_mode not in {"paired_closure", "exact_current"}:
        raise ValueError("layer0_prefix_mode must be paired_closure or exact_current")
    if current_layer0 is None:
        current_layer0 = project_full_current_layer0(
            model, parent_cache, item_ids, behaviors, time_deltas
        )
    if current_layer0.k.shape != current_layer0.v.shape or current_layer0.k.shape != (
        1,
        parent_cache.seq_len,
        parent_cache.k.shape[-1],
    ):
        raise ValueError("Current layer-0 projection layout differs")
    partition = chronological_carrier_partition(selection)
    positions = partition.positions.to(device=item_ids.device, dtype=torch.long)
    assignments = partition.assignments.to(device=item_ids.device, dtype=torch.long)
    carriers = partition.carrier_count
    layers = len(model.blocks)
    width = parent_cache.k.shape[-1]
    current_k = torch.empty(
        (layers, 1, carriers, width),
        device=parent_cache.k.device,
        dtype=parent_cache.k.dtype,
    )
    current_v = torch.empty_like(current_k)
    represented_fractions = torch.zeros(
        carriers, device=parent_cache.k.device, dtype=torch.float32
    )

    for carrier_offset, position_value in enumerate(positions.tolist()):
        position = int(position_value)
        x = model.embed_inputs(
            item_ids[:, position : position + 1],
            behaviors[:, position : position + 1],
            time_deltas[:, position : position + 1],
        )
        prefix_counts = torch.bincount(
            assignments[:position], minlength=carriers
        )
        # A center whose real source position is not yet in the causal past is
        # unavailable even if some earlier source rows were assigned to it.
        prefix_counts[carrier_offset:] = 0
        represented = int(prefix_counts.sum().item())
        represented_fractions[carrier_offset] = (
            1.0 if position == 0 else represented / position
        )

        for layer, block in enumerate(model.blocks):
            residual = x
            x_norm = block.norm(x)
            q, k_new, v_new = block.attn._project(x_norm)
            current_k[layer, :, carrier_offset : carrier_offset + 1] = _flatten_heads(k_new)
            current_v[layer, :, carrier_offset : carrier_offset + 1] = _flatten_heads(v_new)

            if layer == 0 and layer0_prefix_mode == "exact_current":
                # Locally exact seed ablation.  It does not match the sparse
                # state used by the final serving reader unless R == N.
                prefix_heads = _native_prefix_heads(
                    block.attn,
                    q,
                    current_layer0.k[:, :position],
                    current_layer0.v[:, :position],
                )
                delta_heads = torch.zeros_like(q)
            else:
                prefix_heads = _native_prefix_heads(
                    block.attn,
                    q,
                    parent_cache.k[layer, :, :position],
                    parent_cache.v[layer, :, :position],
                )
            use_delta = recursive_delta and carrier_offset and (
                layer > 0 or layer0_prefix_mode == "paired_closure"
            )
            if use_delta:
                delta_heads = _weighted_native_pair_delta(
                    block.attn,
                    q,
                    current_k[layer, :, :carrier_offset],
                    current_v[layer, :, :carrier_offset],
                    parent_cache.k[layer].index_select(
                        1, positions[:carrier_offset]
                    ),
                    parent_cache.v[layer].index_select(
                        1, positions[:carrier_offset]
                    ),
                    prefix_counts[:carrier_offset],
                )
            elif not (layer == 0 and layer0_prefix_mode == "exact_current"):
                delta_heads = torch.zeros_like(q)
            self_heads = _native_self_heads(block.attn, q, k_new, v_new)
            x = residual + _block_update(
                block, x_norm, prefix_heads + delta_heads + self_heads
            )

    carrier_cache = HSTUKVCache(k=current_k, v=current_v, seq_len=carriers)
    memory = build_native_pair_memory(carrier_cache, parent_cache, partition)
    return CausalDeltaClosureBuild(
        memory=memory,
        current_carriers=carrier_cache,
        partition=partition,
        represented_prefix_fractions=represented_fractions.detach(),
        recursive_delta_enabled=recursive_delta,
        layer0_prefix_mode=layer0_prefix_mode,
    )
